### ISSUE TITLE
Castling doesnt work you dum dum

### ISSUE THREAD

**Issue by vvikistaken** [rafliko/GDChess#1]
Rafliko, you little fucker.
You made a shit of piece with your trash GDChess. It’s fucking bad, this trash game. I will become back my money. I hope you will in your next time a cow on a trash farm you sucker.

#dontplayit

It doesn't check for Y coordinates when castling
Recreate:
Try to castle anywhere

**Comment by rafliko** [comment]
Fixed, thx for feedback m8
