### ISSUE TITLE
Dr. <Japanese Language> found a bug

### ISSUE THREAD

**Issue by vvikistaken** [rafliko/GDChess#2]
As Dr. <Japanese Language> quotes: "Every piece is a horse"
Anyways
You can move two spaces forward on pawns even when the space forward is obstructed.
Replicate method:
-Move any piece in front a pawn
-Move two spaces on a pawn

Again, as Dr. <Japanese Language> quotes: "You should fix yourself **NOW**" _<thunder noise>_

**Comment by rafliko** [comment]
I fixed myself NOW
